#!/bin/bash

# HWIMO-BUILD

#
# Build debian package for all images created by on-imagebuilder
#
set -e
output_path=/tmp/on-imagebuilder

# $1 should be a file which contains the release version.
# For example:  PKG_VERSION=1.2.3-rc-abc...
if [ -f "$1" ];then
    source $1
fi

#build static files
sudo ./build_all.sh

#prepare workplace for deb build
rm -rf on-static-common*
rm -rf packagebuild
mkdir packagebuild
pushd packagebuild

mkdir common
mkdir pxe

#copy static files
sudo chmod 644 /tmp/on-imagebuilder/builds/*
sudo chmod 644 /tmp/on-imagebuilder/ipxe/*
sudo chmod 644 /tmp/on-imagebuilder/syslinux/*
sudo cp $output_path/builds/* common/
sudo cp $output_path/syslinux/* pxe/
sudo cp $output_path/ipxe/* pxe/
rsync -av ../debian .

export DEBEMAIL="hwimo robots <hwimo@hwimo.lab.emc.com>"
export DEBFULLNAME="The HWIMO Robots"

if [ ! -z "$PKG_VERSION" ];then
    if [[ $PKG_VERSION =~ ^[0-9.]+$ ]];then
        dch -r ""
    else
        COMMIT_STR=`git log -n 1 --oneline`
        dch -v $PKG_VERSION -u low $COMMIT_STR -b -m
    fi
fi

debuild --no-lintian --no-tgz-check -us -uc
popd
