#!/bin/bash

#
# Build debian package for all images created by on-imagebuilder
#
# Input (environment variables):
# * PKG_VERSION: The version of debian package,
#                such as: 1.3.1 (official release);
#

set -e
output_path=/tmp/on-imagebuilder

#build static files
sudo ./build_all.sh

#prepare workplace for deb build
rm -rf on-static-common*
rm -rf packagebuild
mkdir packagebuild
pushd packagebuild

mkdir common
mkdir pxe

#copy static files
sudo chmod 644 /tmp/on-imagebuilder/builds/*
sudo chmod 644 /tmp/on-imagebuilder/ipxe/*
sudo chmod 644 /tmp/on-imagebuilder/syslinux/*
cp $output_path/builds/* common/
cp $output_path/syslinux/* pxe/
cp $output_path/ipxe/* pxe/
rsync -av ../debian .

export DEBEMAIL="hwimo robots <hwimo@hwimo.lab.emc.com>"
export DEBFULLNAME="The HWIMO Robots"

# If PKG_VERSION is not set as an environment variable
# compute it as below:
if [ -z "$PKG_VERSION" ];then
    GIT_COMMIT_DATE=$(git show -s --pretty="format:%ci")
    DATE_STRING=$(date -d "$GIT_COMMIT_DATE" -u +"%Y%m%dUTC")

    GIT_COMMIT_HASH=$(git show -s --pretty="format:%h")

    CHANGELOG_VERSION=$(dpkg-parsechangelog --show-field Version)

    PKG_VERSION="$CHANGELOG_VERSION-$DATE_STRING-$GIT_COMMIT_HASH"
fi

if [[ $PKG_VERSION =~ ^([0-9]+\.){2}[0-9]+$ ]];then
    # If version looks like 1.2.3, the build is official build.
    # So update the distribution of changelog from "UNRELEASED" to "unstable"
    dch -r ""
else
    COMMIT_STR=`git log -n 1 --oneline`
    dch -v $PKG_VERSION -u low $COMMIT_STR -b -m
fi

debuild --no-lintian --no-tgz-check -us -uc
popd
